# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
#  - board: nice_nano_v2
#    shield: sofle_left
#  - board: nice_nano_v2
#    shield: sofle_right

   - board: piantor_pro_bt_left
     snippet: studio-rpc-usb-uart
     shield: nice_view
     cmake-args: -DCONFIG_ZMK_STUDIO=y
   - board: piantor_pro_bt_right
     shield: nice_view
     snippet: studio-rpc-usb-uart

   - board: piantor_pro_bt_left
     shield: settings_reset
     snippet: studio-rpc-usb-uart
   - board: piantor_pro_bt_right
     shield: settings_reset
     snippet: studio-rpc-usb-uart
